// <auto-generated />
namespace OneMany.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recsv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recsv));
        
        string IMigrationMetadata.Id
        {
            get { return "202103260844292_recsv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
